// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function last(_list) {
  while(true) {
    var list = _list;
    if (list) {
      var t = list[1];
      if (t) {
        _list = t;
        continue ;
      } else {
        return /* Some */[list[0]];
      }
    } else {
      return /* None */0;
    }
  };
}

exports.last = last;
/* No side effect */
