// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function last_two(_list) {
  while(true) {
    var list = _list;
    if (list) {
      var t = list[1];
      if (t) {
        if (t[1]) {
          _list = t;
          continue ;
        } else {
          return /* Some */[/* :: */[
                    list[0],
                    /* :: */[
                      t[0],
                      /* [] */0
                    ]
                  ]];
        }
      } else {
        return /* None */0;
      }
    } else {
      return /* None */0;
    }
  };
}

exports.last_two = last_two;
/* No side effect */
