// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var R02$Reasonml = require("./R02.bs.js");

describe("Problem 2", (function () {
        Jest.test("Empty list", (function () {
                return Jest.Expect[/* toEqual */12](/* None */0, Jest.Expect[/* expect */0](R02$Reasonml.last_two(/* [] */0)));
              }));
        Jest.test("List with one element", (function () {
                return Jest.Expect[/* toEqual */12](/* None */0, Jest.Expect[/* expect */0](R02$Reasonml.last_two(/* :: */[
                                    1,
                                    /* [] */0
                                  ])));
              }));
        return Jest.test("List with >2 elements", (function () {
                      return Jest.Expect[/* toEqual */12](/* Some */[/* :: */[
                                    3,
                                    /* :: */[
                                      4,
                                      /* [] */0
                                    ]
                                  ]], Jest.Expect[/* expect */0](R02$Reasonml.last_two(/* :: */[
                                          1,
                                          /* :: */[
                                            2,
                                            /* :: */[
                                              3,
                                              /* :: */[
                                                4,
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ])));
                    }));
      }));

/*  Not a pure module */
