// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Utility$Reasonml = require("./Utility.bs.js");

describe("Problem 1 test", (function () {
        Jest.test("basic test", (function () {
                return Jest.Expect[/* toEqual */12]("test1", Jest.Expect[/* expect */0](Utility$Reasonml.output1));
              }));
        return Jest.test("test print_option_string in utility", (function () {
                      return Jest.Expect[/* toEqual */12]("None", Jest.Expect[/* expect */0](Utility$Reasonml.output2));
                    }));
      }));

/*  Not a pure module */
