// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function print_option_string(option_string) {
  if (option_string) {
    return option_string[0];
  } else {
    return "None";
  }
}

var output1 = "test1";

var output2 = "None";

exports.print_option_string = print_option_string;
exports.output1 = output1;
exports.output2 = output2;
/* No side effect */
